import { NgModule } from '@angular/core';
import {
  IonAlert,
  IonButton,
  IonButtons,
  IonCard,
  IonCardContent,
  IonContent,
  IonHeader,
  IonIcon,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonPopover,
  IonSegment,
  IonSegmentButton,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTitle,
  IonToolbar,
} from '@ionic/angular/standalone';

@NgModule({
  imports: [
    IonHeader,
    IonToolbar,
    IonContent,
    IonSegment,
    IonLabel,
    IonCard,
    IonList,
    IonItem,
    IonSegmentButton,
    IonAlert,
    IonCardContent,
    IonButton,
    IonTitle,
    IonInput,
    IonIcon,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonButtons,
    IonPopover,
  ],
  exports: [
    IonHeader,
    IonToolbar,
    IonContent,
    IonSegment,
    IonLabel,
    IonCard,
    IonList,
    IonItem,
    IonSegmentButton,
    IonAlert,
    IonCardContent,
    IonButton,
    IonTitle,
    IonInput,
    IonIcon,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonButtons,
    IonPopover,
  ],
})
export class IonicStandaloneModule {}
